
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Nov 27 04:44:49 GMT 2014
//----------------------------------------------------

package Example;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int COMMA = 2;
  public static final int LSQBRACKET = 3;
  public static final int error = 1;
  public static final int NUMBER = 5;
  public static final int RSQBRACKET = 4;
  public static final int EOF = 0;
}

