
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Nov 06 16:25:46 GMT 2017
//----------------------------------------------------

package Example;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int LALPHA = 6;
  public static final int COMMA = 2;
  public static final int LSQBRACKET = 3;
  public static final int error = 1;
  public static final int NUMBER = 5;
  public static final int RSQBRACKET = 4;
  public static final int EOF = 0;
}

